KAMUS_SLANG_GABUNGAN: dict = {
    # Slang Umum
    'cancel': 'batal', 'cancle': 'batal', 'cancelin': 'batal', 'ordernya': 'pesanan', 'order': 'pesan', 'orderan': 'pesanan',
    'nyuruh': 'menyuruh', 'diminta': 'diminta', 'beliin': 'belikan', 'belanja': 'belanja', 'kirim': 'kirim', 'kirimin': 'kirimkan',
    'pickup': 'ambil', 'drop': 'antar', 'dropnya': 'antarkan', 'diblokir': 'diblokir', 'diban': 'diblokir', 'ngelaporin': 'melaporkan',
    'laporan': 'laporan', 'laporin': 'laporkan', 'laporkan': 'laporkan', 'suspend': 'tangguhkan', 'suspended': 'ditangguhkan',
    'dinonaktif': 'dinonaktifkan', 'hapus akun': 'hapus akun', 'tlg': 'tolong', 'tolong': 'tolong', 'transfer': 'transfer',
    'tfr': 'transfer', 'trnsfr': 'transfer', 'tf': 'transfer', 'bayar': 'bayar', 'bayarin': 'bayarkan', 'ganti rugi': 'ganti rugi',
    'refund': 'kembalikan', 'dana': 'dana', 'gopay': 'gopay', 'ovo': 'ovo', 'spay': 'shopeepay', 'shopeepay': 'shopeepay',
    'kaspro': 'kaspro', 'dompet': 'dompet', 'gak': 'tidak', 'ga': 'tidak', 'g': 'tidak', 'gk': 'tidak', 'ngga': 'tidak',
    'nggak': 'tidak', 'enggak': 'tidak', 'udah': 'sudah', 'udh': 'sudah', 'sdh': 'sudah', 'dah': 'sudah', 'blm': 'belum',
    'blum': 'belum', 'blom': 'belum', 'mau': 'mau', 'mw': 'mau', 'bgt': 'sangat', 'banget': 'sangat', 'bngt': 'sangat',
    'kak': 'kakak', 'pak': 'bapak', 'bpk': 'bapak', 'mas': 'mas', 'mba': 'mba', 'org': 'orang', 'tdk': 'tidak', 'utk': 'untuk',
    'dgn': 'dengan', 'dr': 'dari', 'ke': 'ke', 'krn': 'karena', 'karna': 'karena', 'jgn': 'jangan', 'sdg': 'sedang',
    'lg': 'lagi', 'lgi': 'lagi', 'knp': 'kenapa', 'knapa': 'kenapa', 'gmn': 'bagaimana', 'gimana': 'bagaimana', 'mksd': 'maksud',
    'yg': 'yang', 'aja': 'saja', 'dng': 'dengan', 'tp': 'tapi', 'trs': 'terus', 'terus': 'terus', 'trus': 'terus',
    'ntar': 'nanti', 'tar': 'nanti', 'bs': 'bisa', 'bisa': 'bisa', 'hrs': 'harus', 'sy': 'saya', 'kami': 'kami', 'sm': 'sama',
    'kita': 'kita', 'km': 'kamu', 'kamu': 'kamu', 'lo': 'kamu', 'lu': 'kamu', 'anda': 'anda', 'dia': 'dia', 'nya': 'nya',
    'tlng': 'tolong', 'tlong': 'tolong', 'minta': 'minta', 'driver': 'pengemudi', 'drver': 'pengemudi', 'pengemudi': 'pengemudi',
    'ojol': 'ojol', 'grab': 'grab', 'gojek': 'gojek', 'gocar': 'gocar', 'grabcar': 'grabcar', 'gofood': 'gofood',
    'grabfood': 'grabfood', 'customer': 'pelanggan', 'pelanggan': 'pelanggan', 'cs': 'layanan pelanggan', 'admin': 'admin',
    'fiktif': 'palsu', 'fake': 'palsu', 'tipu': 'tipu', 'penipu': 'penipu', 'nipu': 'menipu', 'scam': 'penipuan',
    'jebakan': 'jebakan', 'bonus': 'bonus', 'hadiah': 'hadiah', 'kode': 'kode', 'otp': 'otp', 'pin': 'pin', 'promo': 'promo',
    'note': 'catatan', 'notes': 'catatan', 'cash': 'tunai', 'kes': 'tunai', 'tunai': 'tunai', 'cod': 'cod', 'codnya': 'cod',
    'satpam': 'satpam', 'security': 'satpam', 'sampe': 'sampai', 'nyampe': 'sampai', 'bli': 'beli', 'nnti': 'nanti',
    'gnti': 'ganti', 'tmpt': 'tempat', 'sya': 'saya', 'bwt': 'buat', 'qris': 'qris', 'qrisss': 'qris', 'bg': 'bang',
    'koo': 'kok', 'kk': 'kokak', 'kmn': 'kemana', 'send': 'kirim', 'maksut': 'maksud', 'maksutnya': 'maksudnya', 'woke': 'oke',
    'aj': 'saja', 'krja': 'kerja', 'call': 'telepon', 'blg': 'bilang', 'gpp': 'tidak apa-apa', 'gapapa': 'tidak apa-apa',
    'gakpapa': 'tidak apa-apa', 'bwa': 'bawa', 'sebenernya': 'sebenarnya', 'dicheck': 'dicek', 'otw': 'sedang di jalan',
    'klo': 'kalau', 'kalo': 'kalau', 'pdhl': 'padahal', 'drpd': 'daripada', 'skrg': 'sekarang', 'bkn': 'bukan', 'dpt': 'dapat',
    'ttg': 'tentang', 'cm': 'hanya', 'cmn': 'hanya', 'cuma': 'hanya', 'thx': 'terima kasih', 'tq': 'terima kasih',
    'mksh': 'terima kasih', 'makasih': 'terima kasih', 'bgs': 'bagus', 'mhn': 'mohon', 'gw': 'saya', 'gue': 'saya', 'gua': 'saya',
    'ilang': 'hilang', 'pesen': 'pesan', 'mesen': 'memesan', 'jemput': 'jemput', 'ngejemput': 'menjemput', 'males': 'malas',
    'mending': 'lebih baik', 'anjir': 'astaga', 'bego': 'bodoh', 'gblk': 'bodoh', 'y': 'iya', 'ya': 'iya', 'iyaa': 'iya',
    'ok': 'oke', 'bntr': 'sebentar', 'bentar': 'sebentar', 'smpe': 'sampai', 'nunggu': 'menunggu', 'jg': 'juga', 'tuh': 'itu',
    'nih': 'ini', 'ni': 'ini', 'tu': 'itu', 'pas': 'saat', 'cepet': 'cepat', 'cpt': 'cepat', 'bsok': 'besok', 'maren': 'kemarin',
    'kemaren': 'kemarin', 'bgtu': 'begitu', 'brp': 'berapa', 'brpa': 'berapa', 'dkt': 'dekat', 'jauh': 'jauh', 'kpn': 'kapan',
    'lbh': 'lebih', 'lgsg': 'langsung', 'macet': 'macet', 'mct': 'macet', 'pake': 'pakai', 'pke': 'pakai', 'sbnrnya': 'sebenarnya',
    'sbtlnya': 'sebetulnya', 'sih': 'sih', 'slh': 'salah', 'tau': 'tahu', 'temen': 'teman', 'tmn': 'teman', 'wkt': 'waktu',
    'gini': 'begini', 'gitu': 'begitu', 'bner': 'benar', 'bener': 'benar', 'kyk': 'seperti', 'kayak': 'seperti', 'dlu': 'dulu',

    # Slang Bahasa Jawa
    'aku': 'saya', 'kulo': 'saya', 'aku ki': 'saya ini', 'kula': 'saya', 'awakku': 'diri saya', 'awakmu': 'dirimu',
    'kowe': 'kamu', 'koe': 'kamu', 'sampeyan': 'anda', 'sampean': 'anda', 'smean': 'anda', 'njenengan': 'anda',
    'jenengane': 'namanya', 'kui': 'itu', 'adewe': 'kita', 'awak dhewe': 'kita', 'dheweke': 'dia', 'deweke': 'dia',
    'dekne': 'dia', 'deknen': 'dia', 'dee': 'dia', 'wong iku': 'orang itu', 'cah iki': 'orang ini', 'wong kae': 'orang itu',
    'sedulur': 'saudara', 'dulur': 'saudara', 'lur': 'saudara', 'tulung': 'tolong', 'tulong': 'tolong', 'tulungi': 'tolong',
    'njaluk': 'minta', 'nyuwun': 'minta', 'njaluki': 'minta', 'jaluk': 'minta', 'akon': 'suruh', 'kon': 'suruh', 'dikon': 'disuruh',
    'kongkon': 'suruh', 'ngeterne': 'mengantarkan', 'ngeterke': 'mengantarkan', 'nganter': 'mengantar', 'diterke': 'diantar',
    'digowo': 'dibawa', 'gowo': 'bawa', 'gowonen': 'bawakan', 'njupuk': 'ambil', 'jupuk': 'ambil', 'njupukke': 'ambilkan',
    'njikuk': 'ambil', 'dikei': 'diberikan', 'diparingi': 'diberi', 'maringi': 'memberi', 'wenehi': 'memberi', 'wenehke': 'berikan',
    'tuku': 'beli', 'tukoke': 'belikan', 'tukoni': 'belikan', 'nukoni': 'membeli', 'blonjo': 'belanja', 'mbayar': 'bayar',
    'bayaren': 'bayarkan', 'ngirimi': 'mengirimi', 'ngirimke': 'kirimkan', 'kirimke': 'kirimkan', 'ganti': 'ganti',
    'ngganti': 'mengganti', 'nyicil': 'mencicil', 'ngutang': 'berhutang', 'utang': 'hutang', 'nyilih': 'meminjam',
    'silih': 'pinjam', 'nyilihke': 'pinjamkan', 'mbatalno': 'batalkan', 'mbatalke': 'batalkan', 'batalke': 'batalkan',
    'nolak': 'menolak', 'ditolak': 'ditolak', 'wegah': 'tidak mau', 'emoh': 'tidak mau', 'ora gelem': 'tidak mau',
    'ra gelem': 'tidak mau', 'ragelem': 'tidak mau', 'nglaporke': 'melaporkan', 'dilaporke': 'dilaporkan', 'ngancem': 'mengancam',
    'ngapusi': 'menipu', 'apus': 'tipu', 'ngapus': 'menipu', 'diapusi': 'ditipu', 'ngapusi wong': 'menipu orang', 'do': 'pada',
    'ora': 'tidak', 'ra': 'tidak', 'mboten': 'tidak', 'boten': 'tidak', 'durung': 'belum', 'dereng': 'belum', 'dudu': 'bukan',
    'sanes': 'bukan', 'ojo': 'jangan', 'sampun': 'sudah', 'wis': 'sudah', 'uwis': 'sudah', 'wes': 'sudah', 'ndang': 'segera',
    'enggal': 'segera', 'cepet': 'cepat', 'age': 'segera', 'gage': 'segera', 'buru': 'buru', 'buru-buru': 'terburu-buru',
    'sekarang': 'sekarang', 'saiki': 'sekarang', 'langsung': 'langsung', 'sisan': 'sekalian', 'akeh': 'banyak',
    'sithik': 'sedikit', 'sitik': 'sedikit', 'kabeh': 'semua', 'kabehe': 'semuanya', 'okeh': 'banyak', 'okeh banget': 'sangat banyak',
    'banget': 'sangat', 'tenan': 'sungguh', 'temenan': 'sungguh', 'bener': 'benar', 'nuwunsewu': 'permisi',
    'nyuwun pangapunten': 'minta maaf', 'nyuwun ngapuro': 'minta maaf', 'ngapunten': 'maaf', 'sepurane': 'maaf',
    'apurane': 'maafkan', 'matursuwun': 'terima kasih', 'matur nuwun': 'terima kasih', 'matur suwun': 'terima kasih',
    'makasih': 'terima kasih', 'suwun': 'terima kasih', 'monggo': 'silakan', 'monggo mas': 'silakan mas', 'piye': 'bagaimana',
    'pie': 'bagaimana', 'kepiye': 'bagaimana', 'kepie': 'bagaimana', 'ngendi': 'dimana', 'nangdi': 'dimana', 'neng ndi': 'di mana',
    'nendi': 'dimana', 'kapan': 'kapan', 'sopo': 'siapa', 'sinten': 'siapa', 'opo': 'apa', 'ngopo': 'kenapa', 'piro': 'berapa',
    'pinten': 'berapa', 'menawa': 'jika', 'menowo': 'jika', 'menawi': 'jika', 'nek': 'kalau', 'nek ngono': 'kalau begitu',
    'mergo': 'karena', 'soale': 'karena', 'mergane': 'karena itu', 'ning': 'tapi', 'duwit': 'uang', 'duwet': 'uang', 'duit': 'uang',
    'arto': 'uang', 'arta': 'uang', 'recehan': 'uang receh', 'kembalian': 'kembalian', 'selisih': 'selisih', 'kurang': 'kurang',
    'luwih': 'lebih', 'larang': 'mahal', 'regone': 'harganya', 'rego': 'harga', 'ongkos': 'biaya', 'tak laporke': 'akan saya laporkan',
    'tak kandani': 'akan saya beritahu', 'tak blokir': 'akan saya blokir', 'tak unggah': 'akan saya unggah',
    'tak sebar': 'akan saya sebarkan', 'disebarke': 'disebarkan', 'diunggah': 'diunggah', 'ketok ngono': 'kelihatan begitu',
    'kepepet': 'terdesak', 'angel': 'susah', 'repot': 'repot', 'mangkel': 'kesal', 'nesu': 'marah', 'gelo': 'kecewa',
    'isin': 'malu', 'wedi': 'takut', 'neng': 'di', 'nang': 'di', 'ng': 'di', 'mrono': 'ke sana', 'mrene': 'ke sini',
    'mriki': 'ke sini', 'mriko': 'ke sana', 'nggon': 'tempat', 'papan': 'tempat', 'cedak': 'dekat', 'cerak': 'dekat', 'adoh': 'jauh',
    'kidul': 'selatan', 'lor': 'utara', 'wetan': 'timur', 'kulon': 'barat', 'pinggir': 'pinggir', 'tengah': 'tengah',
    'ngarep': 'depan', 'mburi': 'belakang', 'ngisor': 'bawah', 'nduwur': 'atas', 'opo meneh': 'apa lagi', 'ngono': 'begitu',
    'ngene': 'begini', 'ngono ae': 'begitu saja', 'ae': 'saja', 'ben': 'biar', 'ben ngono': 'biar begitu', 'karang': 'memang',
    'mosok': 'masa', 'jare': 'katanya', 'jarene': 'katanya', 'contohe': 'contohnya', 'maksude': 'maksudnya', 'nggih': 'ya',
    'njih': 'ya', 'nggeh': 'ya', 'gae': 'untuk', 'tulung batalke': 'tolong batalkan', 'tulung cancele': 'tolong batalkan',
    'tulung cancel': 'tolong batalkan', 'ora iso cancel': 'tidak bisa batalkan', 'gak iso cancel': 'tidak bisa batalkan',
    'tulung tukokke': 'tolong belikan', 'tulung jupukke': 'tolong ambilkan', 'tak transfer': 'akan saya transfer',
    'tak bayar': 'akan saya bayar', 'tak kirimi duwit': 'akan saya kirimi uang', 'duwite ora cukup': 'uangnya tidak cukup',
    'dhuwite kurang': 'uangnya kurang', 'akun e diblokir': 'akunnya diblokir', 'akune diblokir': 'akunnya diblokir',
    'nang ngendi': 'di mana', 'seko ngendi': 'dari mana', 'nganti ngendi': 'sampai mana', 'tekan endi': 'sampai mana',
    'wis tekan ngendi': 'sudah sampai mana', 'isih adoh': 'masih jauh', 'iseh adoh': 'masih jauh', 'wis cedak': 'sudah dekat',
    'mangkat saiki': 'berangkat sekarang',
}

STOP_WORDS_JAWA: set = {
    "sing", "seko", "lan", "ra", "raiso", "ora",
    "neng", "ning", "nek", "menowo", "menawa", "ben",
    "ana", "ana ing", "ing", "nang", "gaiso", "iso", "kowe", "koe",
    "iku", "iki", "kae", "kuwi", "kono", "kene", "kui",
    "wis", "wes", "durung", "isih", "lagi", "arep", "meh",
    "saged", "iso", "oleh", "keno", "saget",
    "yo", "ta", "to", "tho", "ki", "lho", "lha",
    "wae", "ae", "bae", "tok", "lah",
    "sampeyan", "sampean", "njenengan"
}